cluster.name: bbkruit

network.host: 0.0.0.0

http.port: ${ESPORT:9200}

node:
  name: ${HOSTNAME}
#network:
#  host: ${ES_NET_HOST}

cluster.routing.allocation.disk.watermark.low: 100gb
cluster.routing.allocation.disk.watermark.high: 50gb
cluster.routing.allocation.disk.watermark.flood_stage: 10gb
cluster.info.update.interval: 1m

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts:
  - 10.149.0.127
  - 10.149.0.124
  - 10.149.0.112
  - 10.149.0.122
  - 10.149.0.123
  - node093
  - fs0
